
sudo: required

dist: precise

language:
  bash

addons:
  postgresql: "9.3"

env:
  global:
    - PGVERSION="9.3"
    - RENCI_FTP_URL=ftp://ftp.renci.org
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg

  matrix:
    - IRODS_VERSION=3.3.1 IRODS_RIP_DIR=/usr/local/irods
    - IRODS_VERSION=4.1.9 PG_PLUGIN_VERSION=1.9 PLATFORM=ubuntu12
    - IRODS_VERSION=4.1.10 PG_PLUGIN_VERSION=1.10 PLATFORM=ubuntu12
    - IRODS_VERSION=4.2.2

before_install:
  # workaround for iRODS buffer overflow
  # see https://github.com/travis-ci/travis-ci/issues/5227
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - ./scripts/download_and_verify_irods.sh

install:
  - ./scripts/install_irods.sh

before_script:
  - ./scripts/configure_irods.sh

script:
  - export PATH=$IRODS_RIP_DIR/iRODS/clients/icommands/bin:$PATH
  - ienv
  - ilsresc -l
  - ils
